server:
  port: 3991
spring:
  application:
    name: cloud-yblog-generate
  #zipkin服务所在地址
  zipkin:
    base-url: http://localhost:9411/
  #配置采样百分比,开发环境可以设置为1，表示全部，生产就用默认
  sleuth:
    sampler:
      probability: 1
  #配置springBoot admin
  boot:
    admin:
      client:
        url:  http://localhost:8901   #这里配置admin server 的地址
        username: root
        password: 18420163207
  redis:
    port: 6379
    password:
    host: localhost
    database: 12     #使用db12
  #springcloud配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848    #单机部署
    sentinel:
      transport:
        port: 8720
        dashboard: localhost:8080
  main:
    allow-bean-definition-overriding: true    #不然多个feign接口连接相同的微服务则会报错
#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

#设置ribbon的超时时间
ribbon:
  ReadTimeout: 8000
  ConnectTimeout: 8000

#自定义扫描包
scan:
  packageName: com.boot.controller

management:
  endpoints:
    web:
      exposure:
        include: "*"

#自动生成代码配置选项
cloud:
  yblog:
    generate:
      generateModel: true #是否生成实体类
      modelSerialize: true #实体类是否序列化
      modelGetterAndSetter: true #是否生成get/set方法
      modelConstructor: true #是否生成构造方法
      modelPackage: com.boot.generate #存放生成的实体类的包名
      #生成实体类的路径（**默认使用这个路径**）
      generateModelPath: C:\\Users\\youzhengjie666\\Desktop\\U\\cloud-yblog\\cloud-yblog-generate\\cloud-yblog-generate3991\\src\\main\\java\\com\\boot




