server:
  port: 8901

spring:
  application:
    name: cloud-yblog-monitor
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"