server:
  port: 2801
spring:
  application:
    name: cloud-yblog-article
  redis:
    port: 6379
    password:
    host: localhost
    database: 12     #使用db12
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_yblog_article?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: 18420163207
    driver-class-name: com.mysql.jdbc.Driver
    #springcloud配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848    #单机部署
    sentinel:
      transport:
        port: 8720
        dashboard: localhost:8080
    #配置seata
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  main:
    allow-bean-definition-overriding: true    #不然多个feign接口连接相同的微服务则会报错


#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

#设置ribbon的超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000





mybatis:
  mapperLocations: classpath:mapper/*.xml

#自定义扫描包
scan:
  packageName: com.boot.controller
management:
  endpoints:
    web:
      exposure:
        include: "*"
