server:
  port: 5301
spring:
  application:
    name: cloud-yblog-system
  #zipkin服务所在地址
  zipkin:
    base-url: http://localhost:9411/
  #配置采样百分比,开发环境可以设置为1，表示全部，生产就用默认
  sleuth:
    sampler:
      probability: 1
  #配置springBoot admin
  boot:
    admin:
      client:
        url:  http://localhost:8901   #这里配置admin server 的地址
        username: root
        password: 18420163207
  redis:
    port: 6379
    password:
    host: localhost
    database: 12
  #    timeout: 50000
  #    connect-timeout: 50000
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_yblog_system?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: 18420163207
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    username: 1550324080@qq.com
    host: smtp.qq.com
    default-encoding: UTF-8
    password: xxx
  #  rabbitmq
  rabbitmq:
    username: guest
    virtual-host: /ems
    password: guest
    host: localhost

  #springcloud配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848    #单机部署
    sentinel:
      transport:
        port: 8720
        dashboard: localhost:8080
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  main:
    allow-bean-definition-overriding: true    #不然多个feign接口连接相同的微服务则会报错


#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

#设置ribbon的超时时间
ribbon:
  ReadTimeout: 8000
  ConnectTimeout: 8000

mybatis:
  mapperLocations: classpath:mapper/*.xml

#自定义扫描包
scan:
  packageName: com.boot.controller
management:
  endpoints:
    web:
      exposure:
        include: "*"
